### ISSUE TITLE
Errors and warnings on fresh install

### ISSUE THREAD

**Issue by thibaudcolas** [CodemateLtd/codemate-blog#19]
Following the instructions from the README, `yarn` outputs the following warnings:

```
warning gatsby > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning gatsby-plugin-sharp > imagemin-webp > cwebp-bin > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning "gatsby > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
warning "gatsby-transformer-remark > graphql-type-json@0.1.4" has unmet peer dependency "graphql@>=0.4.0".
warning "react-responsive-grid > react-component-width-mixin@2.0.0" has unmet peer dependency "react-dom@>=0.14.0".
```

None of these seem to prevent the project from starting though 🙂… at least for what I tried.

Then `yarn start` does not exist – `yarn dev` (or `develop`, which does the same thing) seems to be the right command – either the README or the scripts should be updated.

**Task list to resolve this issue (added by Iiro):**
- [x] resolve error messages
- [ ] verify which one is the right alternative to `yarn start` and update README
- [ ] integrate a CI to make sure the project always builds without errors; see #20. Preferably catch those errors, even if the project builds successfully.
