### ISSUE TITLE
UX/UI RoadMap Ideas

### ISSUE THREAD

**Issue by ragmha** [CodemateLtd/codemate-blog#3]
- [ ] Multiple Authors
- [ ] Image Optimization (Moving it to CDN such as https://cloudinary.com/)
- [ ] Adding Social Sharing Buttons 
- [ ] Cross Post to Medium https://github.com/f0rr0/f0rr0.github.io/blob/dev/src/scripts/medium.js
- [ ] No. of words with reading time
- [ ]  Project Guidelines 
- [ ]  Voting community for discussion whether a feature is required or not

**Comment by roughike** [comment]
About cross-posting to Medium:

Medium already has an import button for importing existing posts from a URL. Usually, it works well. But in my experience, the post must still be manually checked and edited for any quirks. I think that blindly shooting something with an automated script to Medium is not the way to go. :)

I propose that we get rid of the automatical crossposting to Medium todo item, and do it manually instead when needed.
